version: '3.5'

services:
  suits-database:
    image: postgres:11
    expose:
      - 5432
    environment:
      - POSTGRES_USER=suits
      - POSTGRES_PASSWORD=suits
      - POSTGRES_DB=suits

  suits-auth:
    image: jboss/keycloak
    volumes:
      - .tools/realm/suits-ims-realm.json:/tmp/suits-ims-realm.json
    expose:
      - 8080
    ports:
      - 8089:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/suits-ims-realm.json

  app:
    image: openjdk:13-slim
    volumes:
      - ${PWD}/build/libs/suits-api-${TAG}.jar:${PWD}/app.jar
    working_dir: ${PWD}
    user: ${USER_ID}
    ports:
      - 8080:8080
    env_file: .env
    entrypoint: ["java", "-jar", "app.jar"]
    links:
      - suits-database
      - suits-auth