version: '3.5'

services:
  suits-database:
    image: postgres:11
    expose:
      - 5432
    environment:
      - POSTGRES_USER=suits
      - POSTGRES_PASSWORD=suits
      - POSTGRES_DB=suits

  suits-auth:
    image: jboss/keycloak
    volumes:
      - .tools/realm/suits-ims-realm.json:/tmp/suits-ims-realm.json
    expose:
      - 8080
    ports:
      - 8089:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/suits-ims-realm.json