version: '3.5'

services:
  suits-database:
    image: postgres:11
    expose:
      - 5432
    environment:
      - POSTGRES_USER=suits
      - POSTGRES_PASSWORD=suits
      - POSTGRES_DB=suits

  suits-auth:
    image: suitsims/suits-auth:1.0.0
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin